/**
 * Voter ID data loader — returns static voter ID requirements for a given state.
 * Data sourced from NCSL and state Secretary of State websites.
 */

import type { VoterIdData } from "@/types/liveElection";

// Static voter ID data for all 50 states + DC
// Sources: National Conference of State Legislatures, state Secretary of State websites
// Last verified: 2026-04-03

const VOTER_ID_DATA: Record<string, VoterIdData> = {
  AL: {
    state: "AL",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Alabama driver's license",
      "Alabama non-driver ID",
      "Alabama photo voter ID card",
      "US passport",
      "US military ID",
      "State-issued ID",
    ],
    exceptions:
      "Voters without ID may cast a provisional ballot and provide ID within 3 days.",
    provisionalBallot: true,
    provisionalBallotRules: "Must provide acceptable ID within 3 days.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Cell phones prohibited inside polling place.",
    sourceUrl: "https://www.sos.alabama.gov/alabama-votes/voter/photo-id",
    lastVerified: "2026-04-03",
  },
  AK: {
    state: "AK",
    voterIdRequired: true,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "Alaska driver's license",
      "State ID card",
      "Voter ID card",
      "US passport",
      "Military ID",
      "Signed poll book entry if poll worker knows voter",
    ],
    exceptions: "Poll workers may vouch for known voters.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available if ID not presented.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones allowed but may not photograph ballots.",
    sourceUrl: "https://elections.alaska.gov/voters/voter-id/",
    lastVerified: "2026-04-03",
  },
  AZ: {
    state: "AZ",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Arizona driver's license",
      "Arizona non-operating ID",
      "Tribal enrollment card with photo",
      "US military ID",
      "US passport",
      "Any government-issued photo ID",
    ],
    exceptions:
      "Voters without photo ID may present two non-photo IDs (utility bill, bank statement, etc.).",
    provisionalBallot: true,
    provisionalBallotRules:
      "Provisional ballot available; voter must present ID by 5pm on Election Day.",
    phonesAtPolls: false,
    phonesAtPollsDetail:
      "No electioneering within 75 feet; phone use at discretion of precinct worker.",
    sourceUrl: "https://azsos.gov/elections/voting-election/voter-id",
    lastVerified: "2026-04-03",
  },
  AR: {
    state: "AR",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Arkansas driver's license",
      "Arkansas ID card",
      "US passport",
      "US military ID",
      "Concealed carry license",
      "Student photo ID (with proof of enrollment)",
    ],
    exceptions:
      "Voters without ID may cast a provisional ballot and provide ID by noon the Monday after the election.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Must provide ID by noon the Monday after the election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Cell phones not allowed to photograph ballot.",
    sourceUrl:
      "https://www.sos.arkansas.gov/elections/voter-information/voter-id",
    lastVerified: "2026-04-03",
  },
  CA: {
    state: "CA",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "First-time voters only: any government ID, utility bill, bank statement, paycheck, or other document showing name and address",
    ],
    exceptions:
      "Only first-time voters who registered by mail and did not provide ID during registration need to show ID.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Provisional ballot available for all voters who face ID issues.",
    phonesAtPolls: true,
    phonesAtPollsDetail:
      "Phones permitted but may not be used to take photos of marked ballots.",
    sourceUrl: "https://www.sos.ca.gov/elections/voter-registration/",
    lastVerified: "2026-04-03",
  },
  CO: {
    state: "CO",
    voterIdRequired: true,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "Colorado driver's license",
      "Colorado ID card",
      "US passport",
      "Employee ID",
      "Student ID",
      "Military ID",
      "Medicare/Medicaid card",
      "Utility bill",
      "Bank statement",
    ],
    exceptions:
      "Most voters receive ballots by mail; ID required for new voters and in-person voting.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available if ID not presented.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Phones permitted; no ballot photography.",
    sourceUrl: "https://www.coloradosos.gov/voter/pages/pub/home.xhtml",
    lastVerified: "2026-04-03",
  },
  CT: {
    state: "CT",
    voterIdRequired: true,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "Connecticut driver's license",
      "Connecticut non-driver ID",
      "Social Security card",
      "Any document with name and address",
    ],
    exceptions: "First-time voters who registered by mail must show ID.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl:
      "https://portal.ct.gov/SOTS/Election-Services/Voter-Information/Voter-ID",
    lastVerified: "2026-04-03",
  },
  DE: {
    state: "DE",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "Photo ID, utility bill, bank statement, or other document showing name and address (first-time voters only)",
    ],
    exceptions: "Only first-time voters who registered by mail.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones must be silenced; no photography.",
    sourceUrl: "https://elections.delaware.gov/voter/votereg.shtml",
    lastVerified: "2026-04-03",
  },
  DC: {
    state: "DC",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "ID required only for first-time voters who registered by mail",
    ],
    exceptions:
      "Registered voters may vote without ID if poll workers verify registration.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Phones permitted in polling place.",
    sourceUrl: "https://www.dcboe.org/Voters/Register-To-Vote",
    lastVerified: "2026-04-03",
  },
  FL: {
    state: "FL",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Florida driver's license",
      "Florida ID card",
      "US passport",
      "Debit or credit card with photo",
      "Military ID",
      "Student ID",
      "Retirement center ID",
      "Neighborhood association ID",
      "Public assistance ID",
    ],
    exceptions:
      "Voter without ID may cast a provisional ballot and provide ID by 5pm on Election Day.",
    provisionalBallot: true,
    provisionalBallotRules: "ID required by 5pm on Election Day.",
    phonesAtPolls: false,
    phonesAtPollsDetail:
      "Phones not allowed to take photos of the marked ballot.",
    sourceUrl:
      "https://dos.myflorida.com/elections/for-voters/voter-registration/",
    lastVerified: "2026-04-03",
  },
  GA: {
    state: "GA",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Georgia driver's license",
      "Georgia ID card",
      "Passport",
      "Military photo ID",
      "Tribal photo ID",
    ],
    exceptions:
      "Voters without photo ID may cast a provisional ballot and show ID within 3 days.",
    provisionalBallot: true,
    provisionalBallotRules: "Must show ID within 3 business days.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones permitted but no photography of ballot.",
    sourceUrl: "https://sos.ga.gov/page/guide-to-voting-in-georgia",
    lastVerified: "2026-04-03",
  },
  HI: {
    state: "HI",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["Signature comparison used; no ID required"],
    exceptions: "All registered voters may vote; signature must match.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Phones permitted.",
    sourceUrl: "https://elections.hawaii.gov/voters/",
    lastVerified: "2026-04-03",
  },
  ID: {
    state: "ID",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Idaho driver's license",
      "Idaho ID card",
      "Passport",
      "Military ID",
      "Tribal ID",
      "Student ID",
      "Personal affidavit if no ID available",
    ],
    exceptions: "Voter without ID may sign a personal affidavit to vote.",
    provisionalBallot: false,
    provisionalBallotRules:
      "Personal affidavit used instead of provisional ballot.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Phones permitted; no ballot photography.",
    sourceUrl: "https://sos.idaho.gov/elections-division/voter-information/",
    lastVerified: "2026-04-03",
  },
  IL: {
    state: "IL",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["No ID required for registered voters"],
    exceptions:
      "First-time voters who registered by mail and did not provide ID need to show ID.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed in voting booth.",
    sourceUrl: "https://www.elections.il.gov/VotingAndRegistration/",
    lastVerified: "2026-04-03",
  },
  IN: {
    state: "IN",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Indiana driver's license",
      "Indiana ID card",
      "US military ID",
      "US passport",
      "Employee ID issued by US, Indiana, or local government",
    ],
    exceptions:
      "Voters without ID may cast a provisional ballot and provide ID by noon on Election Day.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Must show ID or sign affidavit of indigency/religious objection by noon on day after election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting area.",
    sourceUrl: "https://www.in.gov/sos/elections/voter-information/",
    lastVerified: "2026-04-03",
  },
  IA: {
    state: "IA",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Iowa driver's license",
      "Iowa non-operator ID",
      "Iowa voter ID card",
      "Military ID",
      "US passport",
      "Tribal ID",
    ],
    exceptions:
      "First-time voters or those without ID may vote provisional and verify identity within 3 days.",
    provisionalBallot: true,
    provisionalBallotRules: "Must verify identity within 3 days.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://sos.iowa.gov/elections/voterinformation/voterid.html",
    lastVerified: "2026-04-03",
  },
  KS: {
    state: "KS",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Kansas driver's license",
      "Kansas non-driver ID",
      "Concealed carry license",
      "Military ID",
      "US passport",
      "Government-issued photo ID",
    ],
    exceptions:
      "Voters without photo ID may cast a provisional ballot and show ID by 6pm on Election Day.",
    provisionalBallot: true,
    provisionalBallotRules: "Must show ID by 6pm on Election Day.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in polling booth.",
    sourceUrl: "https://www.sos.ks.gov/elections/elections_voter.html",
    lastVerified: "2026-04-03",
  },
  KY: {
    state: "KY",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Kentucky driver's license",
      "Kentucky state ID",
      "US passport",
      "Military photo ID",
      "Medicare/Medicaid card with photo",
    ],
    exceptions:
      "Voters without ID may vote a provisional ballot and show ID by noon the third day after the election.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Must show ID by noon the third day after election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones permitted in voting booth.",
    sourceUrl: "https://elect.ky.gov/voters/",
    lastVerified: "2026-04-03",
  },
  LA: {
    state: "LA",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Louisiana driver's license",
      "Louisiana state ID",
      "Louisiana Wallet Voter Registration Card with photo",
      "Military ID",
      "US passport",
      "Government-issued photo ID",
    ],
    exceptions:
      "Voters without ID may cast a provisional ballot and present ID within 10 days.",
    provisionalBallot: true,
    provisionalBallotRules: "Must present ID within 10 days.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed to photograph ballot.",
    sourceUrl: "https://www.sos.la.gov/ElectionsAndVoting/Pages/default.aspx",
    lastVerified: "2026-04-03",
  },
  ME: {
    state: "ME",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["No ID required; voters sign poll book"],
    exceptions: "No ID required for registered voters.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not to be used inside voting booth.",
    sourceUrl: "https://www.maine.gov/sos/cec/elec/voter-info/",
    lastVerified: "2026-04-03",
  },
  MD: {
    state: "MD",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["No ID required for registered voters"],
    exceptions: "First-time voters who registered by mail may need to show ID.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones permitted; no ballot photography.",
    sourceUrl: "https://elections.maryland.gov/voter_registration/",
    lastVerified: "2026-04-03",
  },
  MA: {
    state: "MA",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["No ID required for registered voters"],
    exceptions: "Voters sign poll book to verify identity.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Phones permitted.",
    sourceUrl: "https://www.sec.state.ma.us/ele/",
    lastVerified: "2026-04-03",
  },
  MI: {
    state: "MI",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Michigan driver's license",
      "Michigan state ID",
      "Michigan voter registration card",
    ],
    exceptions:
      "Voters without photo ID may sign an affidavit and cast a regular ballot.",
    provisionalBallot: false,
    provisionalBallotRules:
      "Signed affidavit allows regular ballot without ID.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No photography of ballots.",
    sourceUrl: "https://mvic.sos.state.mi.us/Voter/Index",
    lastVerified: "2026-04-03",
  },
  MN: {
    state: "MN",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["No ID required; voters sign poll book or voucher"],
    exceptions: "Vouching allowed — registered voter may vouch for another.",
    provisionalBallot: false,
    provisionalBallotRules: "Same-day registration available.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Phones permitted; no ballot photography.",
    sourceUrl: "https://www.sos.state.mn.us/elections-voting/",
    lastVerified: "2026-04-03",
  },
  MS: {
    state: "MS",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Mississippi driver's license",
      "Mississippi voter ID card",
      "US military ID",
      "Government employee ID",
      "US passport",
      "Government-issued photo ID",
    ],
    exceptions:
      "Religious objection exemption available; must sign affidavit and list reason.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Provisional ballot available; must show ID or affidavit by 5pm on day after election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://www.sos.ms.gov/elections-voting/voter-id",
    lastVerified: "2026-04-03",
  },
  MO: {
    state: "MO",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Missouri driver's license",
      "Missouri non-driver ID",
      "Military ID",
      "US passport",
      "ID issued by Missouri or US government",
    ],
    exceptions:
      "Voters without photo ID may vote a provisional ballot and show ID within 10 days, or sign affidavit.",
    provisionalBallot: true,
    provisionalBallotRules: "Must provide ID or sign affidavit within 10 days.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not permitted in voting booth.",
    sourceUrl: "https://www.sos.mo.gov/elections/goVoteMissouri/",
    lastVerified: "2026-04-03",
  },
  MT: {
    state: "MT",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Montana driver's license",
      "Montana state ID",
      "Montana concealed carry permit",
      "Military ID",
      "US passport",
      "Tribal photo ID",
      "Student ID from Montana college",
    ],
    exceptions:
      "Voters without acceptable ID may sign an oath attesting to identity.",
    provisionalBallot: false,
    provisionalBallotRules: "Signed oath allows regular ballot without ID.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones while voting.",
    sourceUrl: "https://sosmt.gov/elections/",
    lastVerified: "2026-04-03",
  },
  NE: {
    state: "NE",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Nebraska driver's license",
      "Nebraska state ID",
      "US passport",
      "US military ID",
      "Government-issued photo ID",
    ],
    exceptions:
      "Voters without ID may cast a provisional ballot and provide ID by 6pm on Election Day.",
    provisionalBallot: true,
    provisionalBallotRules: "Must provide ID by 6pm on Election Day.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://www.sos.ne.gov/elections/voter-info/",
    lastVerified: "2026-04-03",
  },
  NV: {
    state: "NV",
    voterIdRequired: true,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "Nevada driver's license",
      "Nevada ID card",
      "US passport",
      "Military ID",
      "Utility bill",
      "Bank statement",
      "Government document with name and address",
    ],
    exceptions:
      "Most registered voters receive mail ballots; ID required for in-person early/election day voting.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No photography of ballot.",
    sourceUrl: "https://www.nvsos.gov/sos/elections/voters",
    lastVerified: "2026-04-03",
  },
  NH: {
    state: "NH",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "New Hampshire driver's license",
      "New Hampshire non-driver ID",
      "Military ID",
      "US passport",
      "Student ID",
    ],
    exceptions:
      "Voters without photo ID may sign an affidavit (Challenged Voter Affidavit) to vote a regular ballot.",
    provisionalBallot: false,
    provisionalBallotRules:
      "Challenged Voter Affidavit used instead of provisional ballot.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed to photograph the ballot.",
    sourceUrl: "https://www.sos.nh.gov/elections/voters",
    lastVerified: "2026-04-03",
  },
  NJ: {
    state: "NJ",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["No ID required for registered voters"],
    exceptions: "First-time voters who registered by mail may need to show ID.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed in voting booth.",
    sourceUrl:
      "https://www.state.nj.us/state/elections/voter-registration.html",
    lastVerified: "2026-04-03",
  },
  NM: {
    state: "NM",
    voterIdRequired: true,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "New Mexico driver's license",
      "New Mexico ID card",
      "Tribal photo ID",
      "Utility bill",
      "Bank statement",
      "Government document with name and address",
    ],
    exceptions:
      "Voters may state last four digits of SSN instead of showing ID.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://www.sos.nm.gov/voting-elections/voter-information/",
    lastVerified: "2026-04-03",
  },
  NY: {
    state: "NY",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["No ID required; voters sign poll book"],
    exceptions: "First-time voters who registered by mail may need to show ID.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Affidavit ballot available if name not in poll book.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed in voting booth.",
    sourceUrl: "https://www.elections.ny.gov/VotingInNY.html",
    lastVerified: "2026-04-03",
  },
  NC: {
    state: "NC",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "North Carolina driver's license",
      "North Carolina ID card",
      "US passport",
      "Military ID",
      "Student ID",
      "Tribal enrollment card",
      "Out-of-state driver's license (if registered voter recently moved)",
    ],
    exceptions:
      "Voters without ID may vote a provisional ballot and provide ID by 5pm on canvas day.",
    provisionalBallot: true,
    provisionalBallotRules: "Must provide ID by 5pm on canvas day.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://www.ncsbe.gov/voting",
    lastVerified: "2026-04-03",
  },
  ND: {
    state: "ND",
    voterIdRequired: true,
    idType: "strict-non-photo",
    acceptedIds: [
      "North Dakota driver's license",
      "Non-driver ID",
      "Long-term care certificate",
      "Tribal government ID",
      "Documents with name and residential address",
    ],
    exceptions: "No voter registration required in North Dakota.",
    provisionalBallot: false,
    provisionalBallotRules:
      "No voter registration and no provisional ballots; ID required to vote.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl:
      "https://vip.sos.nd.gov/PortalListDetails.aspx?ptlhPKID=259&ptlPKID=1",
    lastVerified: "2026-04-03",
  },
  OH: {
    state: "OH",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Ohio driver's license",
      "Ohio ID card",
      "US military ID",
      "Ohio photo ID",
    ],
    exceptions:
      "Voters without photo ID may use last four digits of SSN or cast a provisional ballot.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Provisional ballot available; voter must provide ID within 7 days.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed in voting booth.",
    sourceUrl: "https://www.ohiosos.gov/elections/voters/id-requirements/",
    lastVerified: "2026-04-03",
  },
  OK: {
    state: "OK",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Oklahoma driver's license",
      "Oklahoma ID card",
      "US passport",
      "Military photo ID",
      "Government-issued photo ID",
    ],
    exceptions:
      "Voters without photo ID may cast a provisional ballot and provide ID by Friday following election.",
    provisionalBallot: true,
    provisionalBallotRules: "Must provide ID by Friday following the election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in polling place.",
    sourceUrl: "https://www.ok.gov/elections/voter_info/",
    lastVerified: "2026-04-03",
  },
  OR: {
    state: "OR",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "No in-person voting; ballots mailed to all registered voters",
    ],
    exceptions: "Oregon is an all-mail-ballot state. No ID required.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Provisional ballot available for in-person voting.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Drop box voting; no polling place.",
    sourceUrl: "https://sos.oregon.gov/elections/Pages/voteinOR.aspx",
    lastVerified: "2026-04-03",
  },
  PA: {
    state: "PA",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Pennsylvania driver's license",
      "Pennsylvania ID card",
      "US passport",
      "Military ID",
      "Government employee ID",
      "Student ID",
    ],
    exceptions:
      "Only first-time voters at a polling place must show ID. All other voters sign poll book.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed in voting booth.",
    sourceUrl: "https://www.vote.pa.gov/Register-to-Vote/Pages/Voter-ID.aspx",
    lastVerified: "2026-04-03",
  },
  RI: {
    state: "RI",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Rhode Island driver's license",
      "Rhode Island ID card",
      "US passport",
      "Military ID",
      "Government-issued photo ID",
      "Student ID",
    ],
    exceptions:
      "Voters without ID may vote a provisional ballot and show ID within 7 days.",
    provisionalBallot: true,
    provisionalBallotRules: "Must show ID within 7 days.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed in voting booth.",
    sourceUrl: "https://vote.sos.ri.gov/",
    lastVerified: "2026-04-03",
  },
  SC: {
    state: "SC",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "South Carolina driver's license",
      "South Carolina ID card",
      "South Carolina DMV photo ID",
      "US passport",
      "Military photo ID",
    ],
    exceptions:
      "Voters without photo ID may cast a provisional ballot and provide ID by 5pm two days after the election.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Must provide ID by 5pm two days after the election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not permitted inside polling place.",
    sourceUrl: "https://www.scvotes.gov/south-carolina-photo-id-requirements",
    lastVerified: "2026-04-03",
  },
  SD: {
    state: "SD",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "South Dakota driver's license",
      "South Dakota ID card",
      "US passport",
      "Tribal photo ID",
      "Military photo ID",
      "Government-issued photo ID",
    ],
    exceptions:
      "Voters without photo ID may cast a provisional ballot and provide ID by 5pm on the day after the election.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Must provide ID by 5pm on the day after the election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed in voting booth.",
    sourceUrl: "https://sdsos.gov/elections-voting/voting/voter-information/",
    lastVerified: "2026-04-03",
  },
  TN: {
    state: "TN",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Tennessee driver's license",
      "Tennessee photo ID card",
      "US passport",
      "Photo ID issued by Tennessee or US government",
      "US military photo ID",
      "Tennessee handgun carry permit with photo",
    ],
    exceptions:
      "Voters without ID may cast a provisional ballot and provide ID by 2 business days after election.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Must provide ID by 2 business days after election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://sos.tn.gov/elections",
    lastVerified: "2026-04-03",
  },
  TX: {
    state: "TX",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Texas driver's license or ID card",
      "Texas Election Identification Certificate",
      "Texas personal ID card issued by DPS",
      "US military ID card with photo",
      "US citizenship certificate with photo",
      "US passport (book or card)",
      "Texas license to carry a handgun",
    ],
    exceptions:
      "Voters without acceptable ID can sign a Reasonable Impediment Declaration and present alternative ID (utility bill, bank statement, government document with name and address, paycheck, certified birth certificate).",
    provisionalBallot: true,
    provisionalBallotRules:
      "Voters who do not present ID or sign a declaration can cast a provisional ballot and provide ID within 6 calendar days.",
    phonesAtPolls: false,
    phonesAtPollsDetail:
      "Texas law prohibits wireless communication devices in the voting room. You may bring written notes.",
    sourceUrl: "https://www.sos.texas.gov/elections/voter/photo-id.shtml",
    lastVerified: "2026-04-03",
  },
  UT: {
    state: "UT",
    voterIdRequired: true,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "Utah driver's license",
      "Utah ID card",
      "US passport",
      "Military ID",
      "Utah concealed carry permit",
      "Utility bill",
      "Bank statement",
      "Government check/document with name and address",
    ],
    exceptions:
      "Voters may provide last four digits of SSN instead of showing ID.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://vote.utah.gov/",
    lastVerified: "2026-04-03",
  },
  VT: {
    state: "VT",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["No ID required; voters sign poll book"],
    exceptions: "No ID required for registered voters.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Phones permitted.",
    sourceUrl: "https://sos.vermont.gov/elections/voters/",
    lastVerified: "2026-04-03",
  },
  VA: {
    state: "VA",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Virginia driver's license",
      "Virginia ID card",
      "US passport",
      "Military photo ID",
      "Student photo ID",
      "Employee photo ID",
    ],
    exceptions:
      "Voters without photo ID may vote a provisional ballot using the last four digits of their SSN.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Provisional ballot available with last four digits of SSN.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://www.elections.virginia.gov/casting-a-ballot/",
    lastVerified: "2026-04-03",
  },
  WA: {
    state: "WA",
    voterIdRequired: false,
    idType: "non-strict-non-photo",
    acceptedIds: ["All-mail ballot state; no in-person ID required"],
    exceptions: "Washington is an all-mail-ballot state.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: true,
    phonesAtPollsDetail: "Mail voting; no polling place.",
    sourceUrl: "https://www.sos.wa.gov/elections/voters/",
    lastVerified: "2026-04-03",
  },
  WV: {
    state: "WV",
    voterIdRequired: true,
    idType: "non-strict-non-photo",
    acceptedIds: [
      "West Virginia driver's license",
      "West Virginia ID card",
      "US passport",
      "Military ID",
      "Student ID",
      "Utility bill",
      "Bank statement",
    ],
    exceptions:
      "Voters without ID may state last four digits of SSN or be vouched for by a poll worker who knows them.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "Phones not allowed in voting booth.",
    sourceUrl: "https://sos.wv.gov/elections/pages/voterid.aspx",
    lastVerified: "2026-04-03",
  },
  WI: {
    state: "WI",
    voterIdRequired: true,
    idType: "strict-photo",
    acceptedIds: [
      "Wisconsin driver's license",
      "Wisconsin state ID",
      "US military ID",
      "US passport",
      "Tribal photo ID",
      "Student ID (must contain signature and expiration date)",
    ],
    exceptions:
      "Voters without photo ID may cast a provisional ballot and provide ID by 4pm the Friday after the election.",
    provisionalBallot: true,
    provisionalBallotRules:
      "Must provide ID by 4pm the Friday after the election.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://myvote.wi.gov/en-us/VoterID",
    lastVerified: "2026-04-03",
  },
  WY: {
    state: "WY",
    voterIdRequired: true,
    idType: "non-strict-photo",
    acceptedIds: [
      "Wyoming driver's license",
      "Wyoming state ID",
      "US passport",
      "Military ID",
      "Medicare/Medicaid card",
      "Tribal photo ID",
    ],
    exceptions:
      "Voters without photo ID may state their address and last four digits of SSN.",
    provisionalBallot: true,
    provisionalBallotRules: "Provisional ballot available.",
    phonesAtPolls: false,
    phonesAtPollsDetail: "No phones in voting booth.",
    sourceUrl: "https://sos.wyo.gov/elections/",
    lastVerified: "2026-04-03",
  },
};

/**
 * Get voter ID data for a state.
 * Returns null if state not found.
 */
export function getVoterIdData(stateCode: string): VoterIdData | null {
  return VOTER_ID_DATA[stateCode.toUpperCase()] ?? null;
}

/**
 * Get all voter ID data.
 */
export function getAllVoterIdData(): Record<string, VoterIdData> {
  return VOTER_ID_DATA;
}
