#!/usr/bin/env bash
# Pull secrets from Bitwarden Secrets Manager and write .env.local.
#
# This script is shared between local development and the autonomous workflow
# experiment. For the experiment, we use ISOLATED experiment-only credentials
# wherever they exist in BWS — this prevents the 45 builds from blowing through
# launch/production's API budget, rate limits, or data stores.
#
# Isolation map:
#   - Anthropic: experiment workspace key (own spend cap, isolated from prod)
#   - Upstash:   experiment Redis database (isolated keyspace — no test data
#                pollutes prod aggregate counters)
#   - OpenStates / OpenFEC: experiment-only keys (production doesn't use these
#                APIs, but the spec mentions them; keys provisioned just in case
#                a framework integrates them)
#   - Google Civic + Places: SHARED with production (no experiment-only project
#                exists yet). Civic free tier is 25K/day so experiment shouldn't
#                exhaust it. Places has billable behavior past free credit —
#                consider setting per-key daily quotas in Google Cloud Console.
#   - Vote Smart / Democracy Works: NOT provisioned (require demo/expensive).
#                Sub-agents fall back to Anthropic web_search per PHASE3_SPEC.
#
# Usage:
#   ./scripts/load-secrets.sh               # writes .env.local in current dir
#   ./scripts/load-secrets.sh /path/to/dir  # writes .env.local in target dir
#   ./scripts/load-secrets.sh --all         # writes to all 5 sibling worktrees
#
# Requires:
#   bws CLI  — https://github.com/bitwarden/sdk-sm/releases
#   BWS_ACCESS_TOKEN env var (add to ~/.zshrc so it's always available)

set -euo pipefail

# ── secret UUIDs ──────────────────────────────────────────────────────────────
# Experiment-isolated:
UUID_ANTHROPIC_EXP="7b91df7b-d018-46af-b886-b44700ee11a7"
UUID_UPSTASH_URL_EXP="12165e99-73e1-49d7-a785-b44700ed8a6b"
UUID_UPSTASH_TOKEN_EXP="b0938d0f-f34c-4349-8fd4-b44700ed995c"
UUID_OPENSTATES_EXP="0aff56fe-f7f9-4aa4-bfc7-b44700efd2d5"
UUID_OPENFEC_EXP="b16475b7-0434-490c-8f97-b44700f04373"
# Shared with production (no experiment-only equivalent provisioned):
UUID_CIVIC="8737e327-3962-45af-b290-b42a013e1066"
UUID_PLACES="5fb2ebf9-500f-4335-86d5-b42b016051d0"

# ── preflight ─────────────────────────────────────────────────────────────────
TOKEN="${BWS_ACCESS_TOKEN:-}"
if [[ -z "$TOKEN" ]]; then
  echo "Error: BWS_ACCESS_TOKEN is not set." >&2
  echo "  Add to ~/.zshrc:  export BWS_ACCESS_TOKEN=<your-service-account-token>" >&2
  exit 1
fi

if ! command -v bws &>/dev/null; then
  echo "Error: bws CLI not found." >&2
  echo "  Install: https://github.com/bitwarden/sdk-sm/releases/tag/bws-v2.0.0" >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "Error: jq not found. brew install jq" >&2
  exit 1
fi

# ── secret fetch helper ───────────────────────────────────────────────────────
fetch() {
  bws secret get "$1" --access-token "$TOKEN" --output json | jq -r '.value'
}

# ── write .env.local to a single directory ────────────────────────────────────
write_env() {
  local dir="$1"
  if [[ ! -d "$dir" ]]; then
    echo "  Skipping $dir (directory not found)"
    return
  fi

  echo "  Pulling secrets..."
  local ANTHROPIC_VOTER_API GOOGLE_CIVIC_API_KEY NEXT_PUBLIC_GOOGLE_PLACES_API_KEY
  local UPSTASH_REDIS_REST_URL UPSTASH_REDIS_REST_TOKEN OPENSTATES_API_KEY OPENFEC_API_KEY
  ANTHROPIC_VOTER_API=$(fetch "$UUID_ANTHROPIC_EXP")
  GOOGLE_CIVIC_API_KEY=$(fetch "$UUID_CIVIC")
  NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=$(fetch "$UUID_PLACES")
  UPSTASH_REDIS_REST_URL=$(fetch "$UUID_UPSTASH_URL_EXP")
  UPSTASH_REDIS_REST_TOKEN=$(fetch "$UUID_UPSTASH_TOKEN_EXP")
  OPENSTATES_API_KEY=$(fetch "$UUID_OPENSTATES_EXP")
  OPENFEC_API_KEY=$(fetch "$UUID_OPENFEC_EXP")

  cat > "$dir/.env.local" <<EOF
# Generated by scripts/load-secrets.sh — do not commit
# Experiment-isolated credentials (where available). See script header for the
# isolation map and which keys are still shared with launch/production.

# Anthropic — experiment workspace key (own spend cap)
ANTHROPIC_VOTER_API=$ANTHROPIC_VOTER_API
ANTHROPIC_API_KEY=$ANTHROPIC_VOTER_API

# Google APIs — SHARED with launch/production (no experiment project yet)
GOOGLE_CIVIC_API_KEY=$GOOGLE_CIVIC_API_KEY
NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=$NEXT_PUBLIC_GOOGLE_PLACES_API_KEY

# Upstash Redis — experiment-only database (isolated from prod aggregate counters)
UPSTASH_REDIS_REST_URL=$UPSTASH_REDIS_REST_URL
UPSTASH_REDIS_REST_TOKEN=$UPSTASH_REDIS_REST_TOKEN
# Also alias as KV_REST_API_* for any legacy code paths that still reference it
KV_REST_API_URL=$UPSTASH_REDIS_REST_URL
KV_REST_API_TOKEN=$UPSTASH_REDIS_REST_TOKEN

# Optional: OpenStates + OpenFEC — experiment-only (launch/production doesn't use these;
# included so sub-agents can choose to integrate them if a framework's spec interpretation
# wants additional candidate enrichment beyond Civic + Anthropic web_search)
OPENSTATES_API_KEY=$OPENSTATES_API_KEY
OPENFEC_API_KEY=$OPENFEC_API_KEY
EOF

  echo "  .env.local written to $dir"
}

# ── main ──────────────────────────────────────────────────────────────────────
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [[ "${1:-}" == "--all" ]]; then
  WORKTREES=(
    "$REPO_ROOT"
    "$REPO_ROOT/../voter-choice-bmad"
    "$REPO_ROOT/../voter-choice-compound"
    "$REPO_ROOT/../voter-choice-speckit"
    "$REPO_ROOT/../voter-choice-superpowers"
    "$REPO_ROOT/../voter-choice-vanilla"
  )
  for wt in "${WORKTREES[@]}"; do
    echo "→ $wt"
    write_env "$wt"
  done
else
  TARGET="${1:-$PWD}"
  write_env "$TARGET"
fi

echo ""
echo "Done. The .env.local file(s) are gitignored and safe to leave in place."
echo "Re-run this script whenever keys are rotated."
