#!/usr/bin/env bash
# Pull secrets from Bitwarden Secrets Manager and write .env.local.
# Mirrors the "Pull secrets from Bitwarden SM" step in .github/workflows/deploy.yml.
#
# Usage:
#   ./scripts/load-secrets.sh               # writes .env.local in current dir
#   ./scripts/load-secrets.sh /path/to/dir  # writes .env.local in target dir
#   ./scripts/load-secrets.sh --all         # writes to all 5 run5 worktrees
#
# Requires:
#   bws CLI  — https://github.com/bitwarden/sdk-sm/releases
#   BWS_ACCESS_TOKEN env var (add to ~/.zshrc so it's always available)

set -euo pipefail

# ── secret UUIDs (from deploy.yml) ────────────────────────────────────────────
UUID_ANTHROPIC="c569bc18-1095-4532-b5df-b42a00f87c2e"
UUID_CIVIC="8737e327-3962-45af-b290-b42a013e1066"
UUID_PLACES="5fb2ebf9-500f-4335-86d5-b42b016051d0"

# ── preflight ─────────────────────────────────────────────────────────────────
TOKEN="${BWS_ACCESS_TOKEN:-}"
if [[ -z "$TOKEN" ]]; then
  echo "Error: BWS_ACCESS_TOKEN is not set." >&2
  echo "  Add to ~/.zshrc:  export BWS_ACCESS_TOKEN=<your-service-account-token>" >&2
  exit 1
fi

if ! command -v bws &>/dev/null; then
  echo "Error: bws CLI not found." >&2
  echo "  Install: https://github.com/bitwarden/sdk-sm/releases/tag/bws-v2.0.0" >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "Error: jq not found. brew install jq" >&2
  exit 1
fi

# ── secret fetch helper ───────────────────────────────────────────────────────
fetch() {
  bws secret get "$1" --access-token "$TOKEN" --output json | jq -r '.value'
}

# ── write .env.local to a single directory ────────────────────────────────────
write_env() {
  local dir="$1"
  if [[ ! -d "$dir" ]]; then
    echo "  Skipping $dir (directory not found)"
    return
  fi

  echo "  Pulling secrets..."
  local ANTHROPIC_VOTER_API GOOGLE_CIVIC_API_KEY NEXT_PUBLIC_GOOGLE_PLACES_API_KEY
  ANTHROPIC_VOTER_API=$(fetch "$UUID_ANTHROPIC")
  GOOGLE_CIVIC_API_KEY=$(fetch "$UUID_CIVIC")
  NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=$(fetch "$UUID_PLACES")

  cat > "$dir/.env.local" <<EOF
# Generated by scripts/load-secrets.sh — do not commit
ANTHROPIC_VOTER_API=$ANTHROPIC_VOTER_API
ANTHROPIC_API_KEY=$ANTHROPIC_VOTER_API
GOOGLE_CIVIC_API_KEY=$GOOGLE_CIVIC_API_KEY
NEXT_PUBLIC_GOOGLE_PLACES_API_KEY=$NEXT_PUBLIC_GOOGLE_PLACES_API_KEY
EOF

  echo "  .env.local written to $dir"
}

# ── main ──────────────────────────────────────────────────────────────────────
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

if [[ "${1:-}" == "--all" ]]; then
  WORKTREES=(
    "$REPO_ROOT"
    "$REPO_ROOT/../voter-choice-bmad"
    "$REPO_ROOT/../voter-choice-compound"
    "$REPO_ROOT/../voter-choice-speckit"
    "$REPO_ROOT/../voter-choice-superpowers"
    "$REPO_ROOT/../voter-choice-vanilla"
  )
  for wt in "${WORKTREES[@]}"; do
    echo "→ $wt"
    write_env "$wt"
  done
else
  TARGET="${1:-$PWD}"
  write_env "$TARGET"
fi

echo ""
echo "Done. The .env.local file(s) are gitignored and safe to leave in place."
echo "Re-run this script whenever keys are rotated."
