/**
 * Louisiana Ethics Administration Program (LEEC) campaign finance donor ingest.
 *
 * Reads pre-processed contribution data from /tmp/la_contributions.json
 * (generated by running python3 /tmp/la_process.py, which filters the bulk
 * contributions CSV downloaded from ethics.la.gov to LA state legislature candidates).
 *
 * To regenerate the JSON:
 *   1. curl -L -o /tmp/la_contributions_2020_2023.csv 'https://www.ethics.la.gov/Pub/CampFinan/DataDownload/ContributionReports/Contributions_2020_to_2023.csv'
 *   2. python3 /tmp/la_process.py
 *
 * Usage:
 *   DATABASE_URL=<neon> npx tsx scripts/ingest/la-leec-donors.ts [--dry-run]
 */

import * as fs from "node:fs";
import { requireDb } from "../../db/client";
import { candidates, donorAggregates } from "../../db/schema";
import { sql } from "drizzle-orm";
import type { DonorBucketLabel } from "./_bucket-mapping";

const SOURCE = "la_leec_bulk";
const SOURCE_URL = "https://www.ethics.la.gov/CampaignFinanceSearch/ShowPremadereports.aspx";
const ELECTION_CYCLE = "2023";
const DATA_FILE = "/tmp/la_contributions.json";

const DRY_RUN = process.argv.includes("--dry-run");

function norm(s: string): string {
  return s.toUpperCase().replace(/['']/g, "").replace(/[-]/g, " ").replace(/\s+/g, " ").trim();
}

async function main() {
  const db = requireDb();
  console.log(`[la-leec] starting dryRun=${DRY_RUN}`);

  if (!fs.existsSync(DATA_FILE)) {
    console.error(`[la-leec] data file not found: ${DATA_FILE}`);
    console.error(`[la-leec] run: python3 /tmp/la_process.py`);
    process.exit(1);
  }

  const scraped = JSON.parse(fs.readFileSync(DATA_FILE, "utf-8")) as Record<string, Record<string, number>>;
  console.log(`[la-leec] scraped_candidates=${Object.keys(scraped).length}`);

  const dbCandidates = await db
    .select({ id: candidates.id, fullName: candidates.fullName })
    .from(candidates)
    .where(sql`jurisdiction LIKE 'state-LA-%'`);

  console.log(`[la-leec] db_candidates=${dbCandidates.length}`);

  const candByNorm = new Map(dbCandidates.map(c => [norm(c.fullName), c.id]));

  const upsertRows: Array<{ candidateId: string; bucketLabel: DonorBucketLabel; amountTotal: number }> = [];
  let matched = 0;

  for (const [scrapedName, buckets] of Object.entries(scraped)) {
    const candidateId = candByNorm.get(norm(scrapedName));
    if (!candidateId) {
      console.log(`[la-leec] WARNING unmatched: ${scrapedName}`);
      continue;
    }
    matched++;
    for (const [bucket, total] of Object.entries(buckets)) {
      if (total <= 0) continue;
      upsertRows.push({ candidateId, bucketLabel: bucket as DonorBucketLabel, amountTotal: total });
    }
  }

  console.log(`[la-leec] matched=${matched} rows_to_upsert=${upsertRows.length}`);

  if (DRY_RUN || upsertRows.length === 0) {
    console.log(`[la-leec] dry_run — skipping upsert`);
    upsertRows.slice(0, 10).forEach(r => {
      const name = dbCandidates.find(c => c.id === r.candidateId)?.fullName ?? r.candidateId;
      console.log(`  ${name} | ${r.bucketLabel} | $${r.amountTotal.toFixed(2)}`);
    });
    return;
  }

  let upserted = 0;
  for (const row of upsertRows) {
    await db
      .insert(donorAggregates)
      .values({
        candidateId: row.candidateId,
        electionCycle: ELECTION_CYCLE,
        bucketLabel: row.bucketLabel,
        amountTotal: row.amountTotal.toFixed(2),
        source: SOURCE,
        sourceUrl: SOURCE_URL,
        insertedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: [donorAggregates.candidateId, donorAggregates.electionCycle, donorAggregates.bucketLabel],
        set: {
          amountTotal: sql`excluded.amount_total`,
          source: sql`excluded.source`,
          sourceUrl: sql`excluded.source_url`,
          insertedAt: sql`excluded.inserted_at`,
        },
      });
    upserted++;
  }

  console.log(`[la-leec] complete matched=${matched} rows_upserted=${upserted} dry_run=${DRY_RUN}`);
}

main().catch(err => { console.error(err); process.exit(1); });
