/**
 * Mississippi CFPORTAL campaign finance donor ingest.
 *
 * Reads pre-scraped contribution data from /tmp/ms_contributions.json
 * (generated by downloading the Excel export from cfportal.sos.ms.gov
 * Contribution search, 2022-2023 date range, then matching to DB candidates).
 *
 * Note: MS online filing was disabled in 2023; only electronically-filed
 * reports from earlier periods are searchable. Coverage is partial.
 *
 * Usage:
 *   DATABASE_URL=<neon> npx tsx scripts/ingest/ms-cfportal-donors.ts [--dry-run]
 */

import * as fs from "node:fs";
import { requireDb } from "../../db/client";
import { candidates, donorAggregates } from "../../db/schema";
import { sql } from "drizzle-orm";
import type { DonorBucketLabel } from "./_bucket-mapping";

const SOURCE = "ms_cfportal_bulk";
const SOURCE_URL = "https://cfportal.sos.ms.gov/online/portal/cf/page/cf-search/Portal.aspx";
const ELECTION_CYCLE = "2023";
const DATA_FILE = "/tmp/ms_contributions.json";

const DRY_RUN = process.argv.includes("--dry-run");

function norm(s: string): string {
  return s.toUpperCase().replace(/['']/g, "").replace(/[-]/g, " ").replace(/\s+/g, " ").trim();
}

async function main() {
  const db = requireDb();
  console.log(`[ms-cfportal] starting dryRun=${DRY_RUN}`);

  if (!fs.existsSync(DATA_FILE)) {
    console.error(`[ms-cfportal] data file not found: ${DATA_FILE}`);
    process.exit(1);
  }

  const scraped = JSON.parse(fs.readFileSync(DATA_FILE, "utf-8")) as Record<string, Record<string, number>>;
  console.log(`[ms-cfportal] scraped_candidates=${Object.keys(scraped).length}`);

  const dbCandidates = await db
    .select({ id: candidates.id, fullName: candidates.fullName })
    .from(candidates)
    .where(sql`jurisdiction LIKE 'state-MS-%'`);

  console.log(`[ms-cfportal] db_candidates=${dbCandidates.length}`);

  const candByNorm = new Map(dbCandidates.map(c => [norm(c.fullName), c.id]));

  const upsertRows: Array<{ candidateId: string; bucketLabel: DonorBucketLabel; amountTotal: number }> = [];
  let matched = 0;

  for (const [scrapedName, buckets] of Object.entries(scraped)) {
    const candidateId = candByNorm.get(norm(scrapedName));
    if (!candidateId) {
      console.log(`[ms-cfportal] WARNING unmatched: ${scrapedName}`);
      continue;
    }
    matched++;
    for (const [bucket, total] of Object.entries(buckets)) {
      if (total <= 0) continue;
      upsertRows.push({ candidateId, bucketLabel: bucket as DonorBucketLabel, amountTotal: total });
    }
  }

  console.log(`[ms-cfportal] matched=${matched} rows_to_upsert=${upsertRows.length}`);

  if (DRY_RUN || upsertRows.length === 0) {
    console.log(`[ms-cfportal] dry_run — skipping upsert`);
    upsertRows.slice(0, 8).forEach(r => {
      const name = dbCandidates.find(c => c.id === r.candidateId)?.fullName ?? r.candidateId;
      console.log(`  ${name} | ${r.bucketLabel} | $${r.amountTotal.toFixed(2)}`);
    });
    return;
  }

  let upserted = 0;
  for (const row of upsertRows) {
    await db
      .insert(donorAggregates)
      .values({
        candidateId: row.candidateId,
        electionCycle: ELECTION_CYCLE,
        bucketLabel: row.bucketLabel,
        amountTotal: row.amountTotal.toFixed(2),
        source: SOURCE,
        sourceUrl: SOURCE_URL,
        insertedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: [donorAggregates.candidateId, donorAggregates.electionCycle, donorAggregates.bucketLabel],
        set: {
          amountTotal: sql`excluded.amount_total`,
          source: sql`excluded.source`,
          sourceUrl: sql`excluded.source_url`,
          insertedAt: sql`excluded.inserted_at`,
        },
      });
    upserted++;
  }

  console.log(`[ms-cfportal] complete matched=${matched} rows_upserted=${upserted} dry_run=${DRY_RUN}`);
}

main().catch(err => { console.error(err); process.exit(1); });
