/**
 * New Mexico CFIS (Campaign Finance Information System) donor ingest.
 *
 * Reads pre-scraped contribution data from /tmp/nm_contributions.json
 * (generated by running python3 /tmp/nm_scraper.py, which uses the public
 * CFIS API at login.cfis.sos.state.nm.us).
 *
 * To regenerate the JSON:
 *   python3 /tmp/nm_scraper.py
 *
 * Usage:
 *   DATABASE_URL=<neon> npx tsx scripts/ingest/nm-cfis-donors.ts [--dry-run]
 */

import * as fs from "node:fs";
import { requireDb } from "../../db/client";
import { candidates, donorAggregates } from "../../db/schema";
import { sql } from "drizzle-orm";
import type { DonorBucketLabel } from "./_bucket-mapping";

const SOURCE = "nm_cfis_bulk";
const SOURCE_URL = "https://login.cfis.sos.state.nm.us/#/index";
const ELECTION_CYCLE = "2024";
const DATA_FILE = "/tmp/nm_contributions.json";

const DRY_RUN = process.argv.includes("--dry-run");

function norm(s: string): string {
  return s
    .normalize("NFD")
    .replace(/[̀-ͯ]/gu, "")
    .toUpperCase()
    .replace(/['']/g, "")
    .replace(/[-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

async function main() {
  const db = requireDb();
  console.log(`[nm-cfis] starting dryRun=${DRY_RUN}`);

  if (!fs.existsSync(DATA_FILE)) {
    console.error(`[nm-cfis] data file not found: ${DATA_FILE}`);
    console.error(`[nm-cfis] run: python3 /tmp/nm_scraper.py`);
    process.exit(1);
  }

  const scraped = JSON.parse(fs.readFileSync(DATA_FILE, "utf-8")) as Record<string, Record<string, number>>;
  console.log(`[nm-cfis] scraped_candidates=${Object.keys(scraped).length}`);

  const dbCandidates = await db
    .select({ id: candidates.id, fullName: candidates.fullName })
    .from(candidates)
    .where(sql`jurisdiction LIKE 'state-NM-%'`);

  console.log(`[nm-cfis] db_candidates=${dbCandidates.length}`);

  const candByNorm = new Map(dbCandidates.map(c => [norm(c.fullName), c.id]));

  const upsertRows: Array<{ candidateId: string; bucketLabel: DonorBucketLabel; amountTotal: number }> = [];
  let matched = 0;

  for (const [scrapedName, buckets] of Object.entries(scraped)) {
    const candidateId = candByNorm.get(norm(scrapedName));
    if (!candidateId) {
      console.log(`[nm-cfis] WARNING unmatched: ${scrapedName}`);
      continue;
    }
    matched++;
    for (const [bucket, total] of Object.entries(buckets)) {
      if (total <= 0) continue;
      upsertRows.push({ candidateId, bucketLabel: bucket as DonorBucketLabel, amountTotal: total });
    }
  }

  console.log(`[nm-cfis] matched=${matched} rows_to_upsert=${upsertRows.length}`);

  if (DRY_RUN || upsertRows.length === 0) {
    console.log(`[nm-cfis] dry_run — skipping upsert`);
    upsertRows.slice(0, 10).forEach(r => {
      const name = dbCandidates.find(c => c.id === r.candidateId)?.fullName ?? r.candidateId;
      console.log(`  ${name} | ${r.bucketLabel} | $${r.amountTotal.toFixed(2)}`);
    });
    return;
  }

  let upserted = 0;
  for (const row of upsertRows) {
    await db
      .insert(donorAggregates)
      .values({
        candidateId: row.candidateId,
        electionCycle: ELECTION_CYCLE,
        bucketLabel: row.bucketLabel,
        amountTotal: row.amountTotal.toFixed(2),
        source: SOURCE,
        sourceUrl: SOURCE_URL,
        insertedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: [donorAggregates.candidateId, donorAggregates.electionCycle, donorAggregates.bucketLabel],
        set: {
          amountTotal: sql`excluded.amount_total`,
          source: sql`excluded.source`,
          sourceUrl: sql`excluded.source_url`,
          insertedAt: sql`excluded.inserted_at`,
        },
      });
    upserted++;
  }

  console.log(`[nm-cfis] complete matched=${matched} rows_upserted=${upserted} dry_run=${DRY_RUN}`);
}

main().catch(err => { console.error(err); process.exit(1); });
