/**
 * Tennessee TNCamp campaign finance donor ingest.
 *
 * Reads pre-downloaded contribution CSVs from /tmp/tn_all.csv
 * (generated by combining batches from apps.tn.gov/tncamp bulk search
 * for 2024 election year, candidates, all contribution types).
 *
 * Matches Recipient Name (LAST, FIRST format) to DB candidates and
 * aggregates contributions into donor buckets.
 *
 * Usage:
 *   DATABASE_URL=<neon> npx tsx scripts/ingest/tn-camp-donors.ts [--dry-run]
 */

import * as fs from "node:fs";
import * as readline from "node:readline";
import { requireDb } from "../../db/client";
import { candidates, donorAggregates } from "../../db/schema";
import { sql } from "drizzle-orm";
import { mapEmployerToBucket, bucketIndividualByAmount, type DonorBucketLabel } from "./_bucket-mapping";

const SOURCE = "tn_camp_bulk";
const SOURCE_URL = "https://apps.tn.gov/tncamp/public/cesearch.htm";
const _tnCycleIdx = process.argv.indexOf("--election-cycle");
const ELECTION_CYCLE = _tnCycleIdx !== -1 ? (process.argv[_tnCycleIdx + 1] ?? "2024") : "2024";
const _tnFileIdx = process.argv.indexOf("--file");
const DATA_FILE = _tnFileIdx !== -1 ? (process.argv[_tnFileIdx + 1] ?? "/tmp/tn_all.csv") : "/tmp/tn_all.csv";

const DRY_RUN = process.argv.includes("--dry-run");

function norm(s: string): string {
  return s.toUpperCase().replace(/['']/g, "").replace(/[-]/g, " ").replace(/\s+/g, " ").trim();
}

function parseTnName(recipientName: string): { last: string; first: string } | null {
  const commaIdx = recipientName.indexOf(",");
  if (commaIdx < 0) return null;
  // Handle "LAST, JR., FIRST" → last = "LAST JR", first = "FIRST"
  const rawLast = recipientName.substring(0, commaIdx).trim();
  const rest = recipientName.substring(commaIdx + 1).trim();
  // Skip Jr/Sr/III suffixes in the middle
  const parts = rest.split(",").map(s => s.trim());
  let first = parts[0] ?? "";
  let lastFull = rawLast;
  // If first part is a suffix like "JR." or "SR.", skip it
  if (/^(JR|SR|II|III|IV)\.?$/i.test(first)) {
    lastFull = rawLast + " " + first;
    first = parts[1] ?? "";
  }
  return { last: norm(lastFull), first: norm(first) };
}

// Build matcher: TN "LAST, FIRST" → DB fullName
function buildMatcher(dbCandidates: Array<{ id: string; fullName: string }>) {
  const byLast = new Map<string, Array<{ id: string; fullName: string; first: string }>>();

  for (const c of dbCandidates) {
    const parts = norm(c.fullName).split(" ").filter(Boolean);
    const last = parts[parts.length - 1] ?? "";
    const first = parts[0] ?? "";
    if (!byLast.has(last)) byLast.set(last, []);
    byLast.get(last)!.push({ id: c.id, fullName: c.fullName, first });
  }

  const cache = new Map<string, string | null>();

  return function match(recipientName: string): string | null {
    if (cache.has(recipientName)) return cache.get(recipientName) ?? null;

    const parsed = parseTnName(recipientName);
    if (!parsed) { cache.set(recipientName, null); return null; }

    const { last, first } = parsed;
    const candidates = byLast.get(last);
    if (!candidates || candidates.length === 0) { cache.set(recipientName, null); return null; }

    let match: string | null = null;
    if (candidates.length === 1) {
      // Verify first letter
      if (!first || candidates[0].first[0] === first[0]) {
        match = candidates[0].fullName;
      }
    } else {
      // Disambiguate by first name
      for (const cand of candidates) {
        if (first && cand.first[0] === first[0]) {
          match = cand.fullName;
          break;
        }
      }
    }

    cache.set(recipientName, match);
    return match;
  };
}

function classifyContribution(type: string, occupation: string, employer: string, amount: number): DonorBucketLabel | null {
  const t = (type || "").toUpperCase().trim();
  if (t === "INKIND" || t === "IN-KIND") return "Other";

  const employerStr = (employer + " " + occupation).trim();
  if (employerStr.length > 1) {
    const bucket = mapEmployerToBucket(employerStr);
    if (bucket && bucket !== "Other" && bucket !== "Self-funded") return bucket;
  }

  return bucketIndividualByAmount(amount);
}

function parseCsvLine(line: string): string[] {
  const fields: string[] = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"' && line[i + 1] === '"') { field += '"'; i++; }
      else if (ch === '"') inQuotes = false;
      else field += ch;
    } else {
      if (ch === '"') inQuotes = true;
      else if (ch === ',') { fields.push(field); field = ""; }
      else field += ch;
    }
  }
  fields.push(field);
  return fields;
}

async function main() {
  const db = requireDb();
  console.log(`[tn-camp] starting dryRun=${DRY_RUN}`);

  if (!fs.existsSync(DATA_FILE)) {
    console.error(`[tn-camp] data file not found: ${DATA_FILE}`);
    process.exit(1);
  }

  const dbCandidates = await db
    .select({ id: candidates.id, fullName: candidates.fullName })
    .from(candidates)
    .where(sql`jurisdiction LIKE 'state-TN-%'`);

  console.log(`[tn-camp] db_candidates=${dbCandidates.length}`);

  const match = buildMatcher(dbCandidates);
  const candIdByName = new Map(dbCandidates.map(c => [c.fullName, c.id]));

  const aggregates = new Map<string, number>();
  const matched = new Set<string>();
  let rowsScanned = 0;
  let rowsMatched = 0;
  let headers: string[] = [];

  const rl = readline.createInterface({ input: fs.createReadStream(DATA_FILE), crlfDelay: Infinity });

  for await (const line of rl) {
    if (!line.trim()) continue;
    const vals = parseCsvLine(line);

    if (headers.length === 0) {
      headers = vals.map(h => h.trim());
      continue;
    }

    rowsScanned++;
    const row: Record<string, string> = {};
    headers.forEach((h, i) => { row[h] = (vals[i] ?? "").trim(); });

    const recipientName = row["Recipient Name"] ?? "";
    const fullName = match(recipientName);
    if (!fullName) continue;

    const candidateId = candIdByName.get(fullName);
    if (!candidateId) continue;

    const amtStr = (row["Amount"] ?? "").replace(/[$,]/g, "");
    const amount = parseFloat(amtStr) || 0;
    if (amount <= 0) continue;

    const contribType = row["Type"] ?? "";
    const occupation = row["Contributor Occupation"] ?? "";
    const employer = row["Contributor Employer"] ?? "";

    const bucket = classifyContribution(contribType, occupation, employer, amount);
    if (!bucket) continue;

    const key = `${candidateId}::${bucket}`;
    aggregates.set(key, (aggregates.get(key) ?? 0) + amount);
    matched.add(fullName);
    rowsMatched++;
  }

  console.log(`[tn-camp] rows_scanned=${rowsScanned} rows_matched=${rowsMatched}`);
  console.log(`[tn-camp] candidates_matched=${matched.size}`);

  const upsertRows = Array.from(aggregates.entries()).map(([key, total]) => {
    const [candidateId, bucket] = key.split("::");
    return { candidateId, bucketLabel: bucket as DonorBucketLabel, amountTotal: total };
  });

  console.log(`[tn-camp] rows_to_upsert=${upsertRows.length}`);

  if (DRY_RUN || upsertRows.length === 0) {
    console.log(`[tn-camp] dry_run — skipping upsert`);
    upsertRows.slice(0, 10).forEach(r => {
      const name = dbCandidates.find(c => c.id === r.candidateId)?.fullName ?? r.candidateId;
      console.log(`  ${name} | ${r.bucketLabel} | $${r.amountTotal.toFixed(2)}`);
    });
    return;
  }

  let upserted = 0;
  for (const row of upsertRows) {
    await db
      .insert(donorAggregates)
      .values({
        candidateId: row.candidateId,
        electionCycle: ELECTION_CYCLE,
        bucketLabel: row.bucketLabel,
        amountTotal: row.amountTotal.toFixed(2),
        source: SOURCE,
        sourceUrl: SOURCE_URL,
        insertedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: [donorAggregates.candidateId, donorAggregates.electionCycle, donorAggregates.bucketLabel],
        set: {
          amountTotal: sql`excluded.amount_total`,
          source: sql`excluded.source`,
          sourceUrl: sql`excluded.source_url`,
          insertedAt: sql`excluded.inserted_at`,
        },
      });
    upserted++;
  }

  console.log(`[tn-camp] complete candidates_matched=${matched.size} rows_upserted=${upserted} dry_run=${DRY_RUN}`);
}

main().catch(err => { console.error(err); process.exit(1); });
